---
title: "SDS 192: Introduction to Data Science"
author: "Albert Y. Kim"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

<style>
h1{font-weight: 400;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message=FALSE, warning = FALSE, eval = TRUE, 
  fig.width = 16/2, fig.height = 9/2
)

# CRAN R packages:
library(tidyverse)
library(stringr)
library(knitr)
library(lubridate)
library(forcats)
library(fivethirtyeight)
library(nycflights13)
library(gapminder)
library(babynames)
library(scales)
library(moderndive)
library(leaflet)
library(maps)
library(mapproj)

# Install emo package from GitHub for emoji functionality:
# devtools::install_github("hadley/emo")
library(emo)

# Install patchwork package from GitHub for composing ggplots:
# devtools::install_github("thomasp85/patchwork")
library(patchwork)

# Set seed value of random number generator to get "replicable" random numbers.
# Why 76? Because of https://www.youtube.com/watch?v=xjJ7FheCkCU
set.seed(76)
```

<style>
h1{font-weight: 400;}
</style>

***

# Schedule 

**Topics**:

<!--1. Tools of the trade (orange): R, RStudio, R packages, R Markdown, Git & GitHub-->
1. Data visualization (pink): Grammar of Graphics, Five Named Graphs (5NG), color theory.
1. Working with data (blue): data wrangling, importing, and formatting
1. Maps and spatial data (green): Maps and geospatial data.
1. Learning how to learn new data science tools (yellow): SQL, TBD.

Note that while topics and topics dates may change, all problem sets (PS), project, and midterm dates will not. 

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRvggFhESyu_EFxrcFQXsZtdaQqaqcQ6kgWg173WTkTeWV67RWiZ01G8jhJsQ2b5VUVCJqQ8xo6COWM/pubhtml?gid=864197397&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="850"></iframe>

<!--
{target="_blank"}
-->



***


<!--
# Lec 03: Wed 9/11 {#Lec03}

## Announcements

* Problem set 01 posted under [Problem Sets](PS.html)

## Recap of previous lecture

## Today's topics/activities

## Tweet of the day


***
-->



# Lec 02: Mon 9/9 {#Lec02}

## Announcements

* [Syllabus](syllabus.html) finalized.
* Problem Set 01 due this Friday posted under [Problem Sets](PS.html).


## Today's topics/activities

### 1. Chalk talk

* Intro to Slack [slides](static/intro_to_slack.pdf){target="_blank"}
* What is difference between R and RStudio?
* What are R packages?


### 2. In-class exercise

* Set up RStudio Cloud:
    + Click [here](https://rstudio.cloud/spaces/28268/join?access_code=qLpXUY0xlUFnViI1SB0Q%2FWd%2BEBw9zzL%2BC%2B8xe65F){target="_blank"} to join the "SDS192" Workspace.
    + Click on "New Project"
    + Name it "Class Notes"
* Go over ModernDive reading in schedule above. 

About readings in this course:

* You are responsible for completing a lecture's readings before the next lecture. Ex: you are responsible to read all of ModernDive Chapter 1 before Wednesday.
* I teach lectures assuming you have not done the readings beforehand. However, if it suits your learning style better, please do read beforehand.
* While you don't need to turn in your learning check answers, I *highly* recommend you still do them. The solutions are in Appendix D of the book.


***



# Lec 01: Fri 9/6 {#Lec01}

## Announcements

Welcome!

## Today's topics/activities

* My story.
* What this class is about: Answering questions with data.
* Executive summary of syllabus; finalized syllabus will be published next week.
* Coding: it's normal to be `r emo::ji("scream")`




