---
title: "Problem Sets"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message=FALSE, warning = FALSE, eval = TRUE, 
  fig.width = 16/2, fig.height = 9/2
)

# Set seed value of random number generator to get "replicable" random numbers.
# Why 76? Because of https://www.youtube.com/watch?v=xjJ7FheCkCU
set.seed(76)
```

<!--
{target="_blank"}
-->

<style>
h1{font-weight: 400;}
</style>



***

<!--
# Problem set 07 {#PS07}

*Assigned Friday 11/25, due Friday 12/6 at 10:45am on GitHub Classroom.*

1. **Start this problem set early!** That way you will have time to get help at the Spinelli Center tutoring hours if you run into trouble.
1. **I will not answer your questions until you've been to the Spinelli Center Sun-Thurs 7-9pm tutoring hours first.**
    + It will be very difficult for me to help 68 students individually. Please help me spread the workload. If you're stuck, please get help at the Spinelli Center first: that way they can handle the easy questions, leaving only the harder ones for me. I will be asking you if you've already gone to the Spinelli Center first before answering any of your questions.
    + Note that tutoring from 6pm on Tuesday November 26th through noon on Sunday December 1st is cancelled.
1. **GitHub frustrations are normal.** Git and GitHub are extremely powerful tools, but they can be very frustrating at times. This is normal. Check out the title of this [zine](https://gumroad.com/l/oh-shit-git){target="_blank"} made by [Julia Evans](https://twitter.com/b0rk?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor){target="_blank"} for advanced users.

## 1. GitHub component {#PS07_R}

**Note**: I sent an email on Saturday inviting you to the [Fall 2019 SDS192 Intro to Data Science
](https://github.com/192-2019-09-Fall){target="_blank"} GitHub Classroom Organization. Please accept this invitation.

For this PS you will be using the ["Happy Git and GitHub for the useR"](https://happygitwithr.com/){target="_blank"} book to:

1. Get familiar with GitHub. Read:
    + Chapter 1: Why Git? Why GitHub?
1. Install GitHub on your computers and set it up. Read and perform all steps in:
    + ~~Chapter 4: Register a GitHub account~~ You've already done this
    + ~~Chapter 5: Install or upgrade R and RStudio~~ You've already done this
    + Chatper 6: Install Git
    + Chapter 7: Introduce yourself to Git
1. Locate the GitHub repository you created in Lec32. 
    + You should be able to see it [here](https://github.com/192-2019-09-Fall){target="_blank"} and it should be named something like `learning-github-YOUR_GITHUB_USER_NAME`. So for example, my repo would be called `learning-github-rudeboybert`.
    + If you don't see it, accept this [invitation](https://classroom.github.com/a/sgKoAnsq){target="_blank"} to receive one. 
1. "Clone" the above repo into RStudio on your computer. Read and perform all steps in:
    + Chapter 12: Connect RStudio to Git and GitHub. **For Section 12.2** ignore what's in the book and do the following:
        1. You will not "Make a repo on GitHub," but rather use the `learning-github-YOUR_GITHUB_USER_NAME` repo from the previous step. 
        1. Click the big green button "Create repository."
        1. Copy the HTTPS clone URL to your clipboard via the green “Clone or Download” button.
1. You do not need to submit anything. Completing Chapter 12 will automatically update your submission on GitHub classroom.  


## 2. Hint {#PS07hint}

How do I know if I've successfully completed the assignment?

1. Go to the [SDS192 Intro to Data Science](https://github.com/192-2019-09-Fall) GitHub organization and make sure you see your `learning-github-YOUR_GITHUB_USER_NAME` folder.
1. Then go to your `learning-github-YOUR_GITHUB_USER_NAME` folder and then look at your README. There should be the line "This is a line from RStudio" on it. 



***



# Problem set 06 {#PS06}

*Assigned Monday 11/11. Two components:*

* **R component**. A `.zip` file of your `PS06` RStudio Project folder. Due on Friday 11/15 at 10:45am on Moodle.
* **Quiz**. In-class on Monday 11/18. To do: Read the following Buzzfeed.com [article](https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup){target="_blank"} on DataCamp (an online platform for learning data science). We'll be having a brief in-class ethics discussion based on this article. **Added Sun 11/17**: For context, DataCamp is an online and interactive platform for learning data science, featuring [courses in R, python, SQL, and git](https://www.datacamp.com/search){target="_blank"}. 


## 1. R Markdown component {#PS06_R}

Learning goals:

* Get experience with maps by reproducing the two plots shown in this [example](http://rpubs.com/rudeboybert/PS06){target="_blank"}.
* Understand absolute vs relative file paths
* Start creating work that's reproducible

To do:

* Download the following template ~~`.Rmd` file~~ RStudio Project Folder: <a href="static/PS/PS06.zip" download>`PS06.zip`</a>.
* **Be sure to be in RStudio Project mode**
* Knit it once and read over the instructions.
* Complete the problem set.
* Submit a `.zip` file of all the contents of your `PS06` RStudio Project folder on [Moodle](https://moodle.smith.edu/course/view.php?id=35357){target="_blank"}. 

**Hints**:

1. If your R Markdown file won't "knit", go through these [6 R Markdown Fixes](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/){target="_blank"} first, then seek assistance. In my experience, these 6 fixes resolve 85% of issues.


## 2. Solutions & (imperfect) rubric {#PS06_solutions}

**Solution**:

Copy this <a href="static/PS/PS06_solutions.Rmd" download>`PS06_solutions.Rmd`</a> R Markdown solutions file and put it in your `PS06` RStudio Project folder.

**Rubric**:

1. Quiz: 2 pts
1. R component:
    + Is your `PS06.Rmd` reproducible by the graders? 4 pts (we will be strict on this)
    + Are your two graphs identical to ones in the [example](http://rpubs.com/rudeboybert/PS06){target="_blank"}? 6 pts

Total: 12pts



***



# Problem set 05 {#PS05}

*Assigned Friday 10/18, due Friday 10/25 at 10:45am on Moodle.*


## 1. R Markdown component {#PS05_R}

* Read solutions to previous PS: [`PS04_solutions.html`](static/PS/PS04_solutions.html){target="_blank"} html report.
* Download the following Rmd template file: <a href="static/PS/PS05.Rmd" download>`PS05.Rmd`</a>.
* Knit it once and read over the instructions.
* Complete the problem set.
* Submit the resulting `PS05.html` file on [Moodle](https://moodle.smith.edu/course/view.php?id=35357){target="_blank"}. Note: you are only submitting the output HTML report file and not the original R Markdown file.

**Hints**:

1. If your R Markdown file won't "knit", go through these [6 R Markdown Fixes](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/){target="_blank"} first, then seek assistance. In my experience, these 6 fixes resolve 85% of issues.


## 2. Solutions & (imperfect) rubric {#PS05_solutions}

**Solution**:

* <a href="static/PS/PS05_solutions.Rmd" download>`PS05_solutions.Rmd`</a> R Markdown "source code" to create html report output. 
* [`PS05_solutions.html`](static/PS/PS05_solutions.html){target="_blank"} html report.

**Rubric**:

As stated in lecture, you must *always* labels your axes and add a title. This makes the context of the data easy to understand for the reader.

1. Q1: 3 + 1 + (3 + 2 + 1) = 10pts
1. Q2: 2 + 2 (+ 2 Bonus) = 4pts

Total: 14pts



***



# Problem set 04 {#PS04}

*Assigned Friday 10/11, due Friday 10/18 at 10:45am on Moodle.*


## 1. R Markdown component {#PS04_R}

* Read solutions to previous PS: [`PS03_solutions.html`](static/PS/PS03_solutions.html){target="_blank"} html report.
* Download the following Rmd template file: <a href="static/PS/PS04.Rmd" download>`PS04.Rmd`</a>.
* Knit it once and read over the instructions.
* Complete the problem set.
* Submit the resulting `PS04.html` file on [Moodle](https://moodle.smith.edu/course/view.php?id=35357){target="_blank"}. Note: you are only submitting the output HTML report file and not the original R Markdown file.

**Hints**:

1. If your R Markdown file won't "knit", go through these [6 R Markdown Fixes](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/){target="_blank"} first, then seek assistance. In my experience, these 6 fixes resolve 85% of issues.


## 2. Solutions & (imperfect) rubric {#PS04_solutions}

**Solution**:

* <a href="static/PS/PS04_solutions.Rmd" download>`PS04_solutions.Rmd`</a> R Markdown "source code" to create html report output. 
* [`PS04_solutions.html`](static/PS/PS04_solutions.html){target="_blank"} html report.

**Rubric**:

1. Q1: 2 + 5 + 2 = 9pts
1. Bonus: 1 + 1 = 2pts

Total: 9pts



***
-->



# Problem set 03 {#PS03}

*Due Tuesday 9/28 9pm*

## 1. R Markdown component {#PS03_R}

* Download the following Rmd template file: <a href="static/PS/PS03.Rmd" download>`PS03.Rmd`</a>.
* You will be submitting the resulting `PS03.pdf` file on gradescope. Please use the "Knit to PDF" method directly, instead of "Knit to Word" and then save to PDF method.
* Complete the individual questions. Knit early, knit often.
* If you encounter issues knitting your document, consult the [6 R Markdown Fixes](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/){target="_blank"}.
* Submit on [gradescope](https://www.gradescope.com/courses/308310){target="_blank"}:
    1. Anytime between Mon 9/20 5pm and Tue 9/29 9pm
    1. For each questions, tag **all** pages of your PDF that relate to that question (not just the first)
    1. You will be asked to tag the honor code question as well.

<!--

## 2. Podcast quiz component

Listen to the Not So Standard Deviations podcast episode 71 "Compromised Shoe Situation" (1h4m) available [here](https://overcast.fm/+FMBuKdMEI/){target="_blank"}. In class on Friday 9/27, you'll be giving a brief quiz on this podcast.

Notes:

1. The quiz will not be difficult. As long as you listen to the podcast once, you'll be fine.
1. IMO you don't need to take notes. Listen while folding laundry or exercising! 
1. This podcast relates to "data collection", which will be a theme for Mini-Project 1.



## 3. Solutions & (imperfect) rubric {#PS03_solutions}

**Solution**:

* <a href="static/PS/PS03_solutions.Rmd" download>`PS03_solutions.Rmd`</a> R Markdown "source code" to create html report output. 
* [`PS03_solutions.html`](static/PS/PS03_solutions.html){target="_blank"} html report.

**Rubric**:

1. Q1: 1 + 4 + 1 = 6pts
1. Q2: 1 + 2 + 1 + 3 + 1 = 8pts
1. Podcast quiz: 1pt
-->



***




# Problem set 02 {#PS02}

*Due Monday 9/20 5pm*

## 1. R Markdown component {#PS02_R}

* Download the following Rmd template file: <a href="static/PS/PS02.Rmd" download>`PS02.Rmd`</a>.
* You will be submitting the resulting `PS02.pdf` file on gradescope. There are two methods to create a PDF:
    1. "Knit to PDF". This is the preferred format (for consistency for the graders). 
    1. If this doesn't work for you, then "Knit to Word" and then export/save as PDF
* Complete the individual questions. Knit early, knit often.
* If you encounter issues knitting your document, consult the [6 R Markdown Fixes](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/){target="_blank"}.
* Submit on [gradescope](https://www.gradescope.com/courses/308310){target="_blank"}:
    1. Anytime between Mon 9/13 5pm and Mon 9/20 5pm
    1. For each questions, tag **all** pages of your PDF that relate to that question (not just the first)



## 2. Solutions & (imperfect) rubric {#PS02_solutions}

* <a href="static/PS/PS02_solutions.Rmd" download>`PS02_solutions.Rmd`</a> R Markdown "source code" 
* [`PS02_solutions.pdf`](static/PS/PS02_solutions.pdf){target="_blank"} PDF



***



# Problem set 01 {#PS01}

*Due Monday 9/13 5pm*

1. If you haven't already, complete the [intro survey](https://docs.google.com/forms/d/e/1FAIpQLSdA6uWnig5oR3ITCsVBFDxC6IC5Nq1tYzo-atdChe8CVTTqag/viewform){target="_blank"} distributed on Friday.
1. Complete a syllabus quiz.
    + Open the following [Google Doc](https://docs.google.com/document/d/1WknUhbtDeTGw8vvO8ytTURkF1_72ve4UXF5-SPk5NO8/){target="_blank"} and in the menu bar click "File -> Make a copy..."
    + Answer the questions based on information in the [syllabus](syllabus.html).
1. Submit a PDF of your syllabus quiz responses on gradescope:
    + Your gradescope account is based on your Smith, 5 College, or other official email.
    + Create your account on gradescope via the email sent to you this morning. If you did not receive such an email, add yourself to the course using Entry Code: 6PNXZ5.
    + Log into [gradescope](https://www.gradescope.com/courses/308310){target="_blank"} 
    + **Added after lecture**: You can edit gradescope submissions as many times as you like before the due date/time.
    + **Added after lecture**: You need to "tag" the 11 individual questions on whatever page(s) they are on (demo on Fri 9/10)
    



