<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Midterms</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="static/images/192.png">

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">SDS192</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://sds192fall2019.slack.com/">
    <span class="fa fa-slack fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://moderndive.netlify.com/">ModernDive</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="syllabus.html">Syllabus</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Midterms</h1>

</div>


<!--
{target="_blank"}
-->
<style>
h1{font-weight: 400;}
</style>
<hr />
<div id="midtermI" class="section level1">
<h1>Midterm I</h1>
<div id="administrative-notes" class="section level2">
<h2>Administrative notes</h2>
<ul>
<li><p><strong>Friday 10/4 5pm through Sunday 10/6 11:55pm</strong>. You must submit your midterm no later than Sunday at 11:55pm.</p></li>
<li><p>Instructions on taking exams for <a href="https://sophia.smith.edu/edtech/documentation/print-an-exam-from-the-direct-to-queue-application/" target="_blank">Smithies</a> and <a href="https://sophia.smith.edu/edtech/documentation/special-instructions-for-five-college-and-high-school-students-using-direct-to-queue-exam-printing/" target="_blank">Five College Students</a>. <strong>Print the exam in color.</strong></p></li>
<li><p>Notes for before exam:</p>
<ul>
<li>Link to print exam in the Seelye basement lab is posted on Moodle.</li>
<li>Bring colored pencils/pens.</li>
<li>You do not need a calculator.</li>
<li>Print exam in color.</li>
</ul></li>
<li><p>Notes for during exam:</p>
<ul>
<li>Closed-book, no internet, and individually completed.</li>
<li>You will be given 140 mins to complete it (including transit time to writing area), however I try to time it so that it will take much less than that. In other words, you should have plenty of time to complete it without rushing.</li>
<li><strong>Timestamps will be strictly enforced. Any timestamps indicating than more than 140 minutes are subject to a 50% penalty and an honor board case.</strong></li>
<li>In case of potential errors or ambiguity on the exam, please note them, state your assumptions, and use your best judgement.</li>
</ul></li>
<li><p>Notes for after exam:</p>
<ul>
<li>Be sure to timestamp your exam before returning.</li>
<li>Insert exam in appropriately labeled box in hallway.</li>
</ul></li>
</ul>
</div>
<div id="topics" class="section level2">
<h2>Topics</h2>
<ul>
<li>Topics: Lectures 1-10 inclusive (up to and including color theory in-class exercises).</li>
<li>What to study:
<ul>
<li>Practice midterm posted on Slack. We’ll go over them in Wednesday’s lecture.</li>
<li>Lecture notes: both “chalk talk” and what’s on webpage.</li>
<li>Problem sets and solutions.</li>
<li>ModernDive readings and learning checks.</li>
</ul></li>
</ul>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<p>Boxplot of scores (out of 34) with no whiskers below. Quartiles were 30.12 / 32 / 33.</p>
<p><img src="static/images/midterm_I_distribution.png" width="750" /></p>
</div>
<div id="visualizations-from-midterm" class="section level2">
<h2>Visualizations from midterm</h2>
<p>Question 2.b):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3"></a>example &lt;-<span class="st"> </span><span class="kw">tibble</span>(</span>
<span id="cb1-4"><a href="#cb1-4"></a>  <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;D&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;C&quot;</span>), </span>
<span id="cb1-5"><a href="#cb1-5"></a>  <span class="dt">fruit =</span> <span class="kw">c</span>(<span class="st">&quot;apple&quot;</span>, <span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;orange&quot;</span>),</span>
<span id="cb1-6"><a href="#cb1-6"></a>  <span class="dt">city =</span> <span class="kw">c</span>(<span class="st">&quot;Toronto&quot;</span>, <span class="st">&quot;Montreal&quot;</span>, <span class="st">&quot;Toronto&quot;</span>, <span class="st">&quot;Montreal&quot;</span>),</span>
<span id="cb1-7"><a href="#cb1-7"></a>  <span class="dt">number =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb1-8"><a href="#cb1-8"></a>)</span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> example, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> type, <span class="dt">y =</span> number)) <span class="op">+</span></span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb1-12"><a href="#cb1-12"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Type&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Number&quot;</span>)</span></code></pre></div>
<p><img src="midterms_files/figure-html/unnamed-chunk-2-1.png" width="768" /></p>
<p>Question 2.c):</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> example, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> fruit)) <span class="op">+</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span></span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Fruit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Number&quot;</span>)</span></code></pre></div>
<p><img src="midterms_files/figure-html/unnamed-chunk-3-1.png" width="768" /></p>
<p>Question 2.d):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> example, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> fruit, <span class="dt">y =</span> number, <span class="dt">fill =</span> city)) <span class="op">+</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Fruit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Number&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;City&quot;</span>)</span></code></pre></div>
<p><img src="midterms_files/figure-html/unnamed-chunk-4-1.png" width="768" /></p>
<p>Question 3:</p>
<p><img src="midterms_files/figure-html/unnamed-chunk-5-1.png" width="768" /></p>
<p>Question 4, modified to show difference in proportion</p>
<p><img src="midterms_files/figure-html/unnamed-chunk-6-1.png" width="768" /></p>
<hr />
</div>
</div>
<div id="midtermII" class="section level1">
<h1>Midterm II</h1>
<div id="administrative-notes-1" class="section level2">
<h2>Administrative notes</h2>
<ul>
<li><p><strong>Friday 11/8 5pm through Sunday 11/10 11:55pm</strong>. You must submit your midterm no later than Sunday at 11:55pm.</p></li>
<li><p>Instructions on taking exams for <a href="https://sophia.smith.edu/edtech/documentation/print-an-exam-from-the-direct-to-queue-application/" target="_blank">Smithies</a> and <a href="https://sophia.smith.edu/edtech/documentation/special-instructions-for-five-college-and-high-school-students-using-direct-to-queue-exam-printing/" target="_blank">Five College Students</a>. <strong>Print the exam in color.</strong></p></li>
<li><p>Notes for before exam:</p>
<ul>
<li>Link to print exam in the Seelye basement lab is posted on Moodle.</li>
<li>Bring colored pencils/pens.</li>
<li>You do not need a calculator.</li>
<li>Print exam in color.</li>
</ul></li>
<li><p>Notes for during exam:</p>
<ul>
<li>Closed-book, no internet, and individually completed.</li>
<li>You will be given 140 mins to complete it (including transit time to writing area), however I try to time it so that it will take much less than that. In other words, you should have plenty of time to complete it without rushing.</li>
<li><strong>Timestamps will be strictly enforced. Any timestamps indicating than more than 140 minutes are subject to an honor board case and depending on decision a 50% penalty.</strong></li>
<li>In case of potential errors or ambiguity on the exam, please note them, state your assumptions, and use your best judgement.</li>
</ul></li>
<li><p>Notes for after exam:</p>
<ul>
<li>Be sure to timestamp your exam before returning.</li>
<li>Insert exam in appropriately labeled box in hallway.</li>
</ul></li>
</ul>
</div>
<div id="topics-1" class="section level2">
<h2>Topics</h2>
<ul>
<li>Topics:
<ul>
<li>Lecture 10-12. Last few topics on Data viz: Color theory, trend lines. <strong>Added on 11/6</strong>: No Shiny apps.</li>
<li>Lecture 14-20. Data wrangling, “tidy” data, and importing data.</li>
</ul></li>
<li>Themes:
<ul>
<li>The midterm is not “cummulative” in the sense that the focus will be on Lectures 10-20, but you still need to know/understand topics from Midterm I because the materials build on top of each other.</li>
<li>Know how to write <em>pseudocode</em> like in the Available Seat Miles exercise in Lecture 19 on Wed 10/23. Click <a href="https://twitter.com/rudeboybert/status/964181298691629056" target="_blank">here</a> for examples. Pseudocode is both:
<ul>
<li>Just general enough to apply to any programming language/statistical software: R, python, SPSS, STATA, SAS, etc.</li>
<li>Just specific enough that the instructions are unambigious</li>
</ul></li>
<li>Know the difference between these five joins: <code>left_join()</code>, <code>right_join()</code>, <code>inner_join()</code>, <code>full_join()</code>, and <code>anti_join()</code>. Go over the code examples on the course webpage for <a href="index.html#Lec19">Lec19</a>.</li>
</ul></li>
<li>What to study. Here is my suggested order:
<ul>
<li>Practice midterm posted on Slack under <code>#general_announcement</code>: this will give you a feel for the types of questions to expect.</li>
<li>Read chalk talk notes: they emphasize/summarize the most important ideas.</li>
<li>ModernDive Learning Check 3.20 on available seat miles (solutions in Appendix D): this is an all-encompassing problem that draws on nearly all the data wrangling verbs we’ve seen.</li>
<li>ModernDive readings and learning checks: In particular the more theoretical ideas of “tidy” data.</li>
<li>Problem sets 04 and 05</li>
</ul></li>
</ul>
</div>
<div id="practice-midterm-notes" class="section level2">
<h2>Practice midterm notes</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="kw">library</span>(fivethirtyeight)</span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="kw">library</span>(nycflights13)</span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="kw">library</span>(babynames)</span></code></pre></div>
<div id="question-1" class="section level3">
<h3>Question 1</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>babynames</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 × 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724
##  2  1880 F     Anna       2604 0.0267
##  3  1880 F     Emma       2003 0.0205
##  4  1880 F     Elizabeth  1939 0.0199
##  5  1880 F     Minnie     1746 0.0179
##  6  1880 F     Margaret   1578 0.0162
##  7  1880 F     Ida        1472 0.0151
##  8  1880 F     Alice      1414 0.0145
##  9  1880 F     Bertha     1320 0.0135
## 10  1880 F     Sarah      1288 0.0132
## # … with 1,924,655 more rows</code></pre>
</div>
<div id="question-2" class="section level3">
<h3>Question 2</h3>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">nrow</span>(weather)</span></code></pre></div>
<pre><code>## [1] 26115</code></pre>
</div>
<div id="question-4" class="section level3">
<h3>Question 4</h3>
<p>Based on <a href="https://fivethirtyeight.com/features/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/" target="_blank">Dear Mona Followup: Where Do People Drink The Most Beer, Wine And Spirits?</a>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># drinks is not &quot;tidy&quot;</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>drinks</span></code></pre></div>
<pre><code>## # A tibble: 193 × 5
##    country           beer_servings spirit_servings wine_servings total_litres_of…
##    &lt;chr&gt;                     &lt;int&gt;           &lt;int&gt;         &lt;int&gt;            &lt;dbl&gt;
##  1 Afghanistan                   0               0             0              0  
##  2 Albania                      89             132            54              4.9
##  3 Algeria                      25               0            14              0.7
##  4 Andorra                     245             138           312             12.4
##  5 Angola                      217              57            45              5.9
##  6 Antigua &amp; Barbuda           102             128            45              4.9
##  7 Argentina                   193              25           221              8.3
##  8 Armenia                      21             179            11              3.8
##  9 Australia                   261              72           212             10.4
## 10 Austria                     279              75           191              9.7
## # … with 183 more rows</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>drinks_tidy &lt;-<span class="st"> </span>drinks <span class="op">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="st">  </span><span class="co"># Convert to &quot;tidy&quot;</span></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">ends_with</span>(<span class="st">&quot;servings&quot;</span>), <span class="dt">names_to =</span> <span class="st">&quot;type&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;servings&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="st">  </span><span class="co"># Do text manipulation: only characters 1 thru 10. this trims off &quot;_servings&quot;</span></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">type =</span> <span class="kw">str_sub</span>(type, <span class="dt">start=</span><span class="dv">1</span>, <span class="dt">end=</span><span class="op">-</span><span class="dv">10</span>)) <span class="op">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6"></a><span class="st">  </span><span class="kw">arrange</span>(country, type)</span>
<span id="cb11-7"><a href="#cb11-7"></a>drinks_tidy</span></code></pre></div>
<pre><code>## # A tibble: 579 × 4
##    country     total_litres_of_pure_alcohol type   servings
##    &lt;chr&gt;                              &lt;dbl&gt; &lt;chr&gt;     &lt;int&gt;
##  1 Afghanistan                          0   beer          0
##  2 Afghanistan                          0   spirit        0
##  3 Afghanistan                          0   wine          0
##  4 Albania                              4.9 beer         89
##  5 Albania                              4.9 spirit      132
##  6 Albania                              4.9 wine         54
##  7 Algeria                              0.7 beer         25
##  8 Algeria                              0.7 spirit        0
##  9 Algeria                              0.7 wine         14
## 10 Andorra                             12.4 beer        245
## # … with 569 more rows</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="kw">ggplot</span>(drinks_tidy, <span class="kw">aes</span>(<span class="dt">x =</span> type, <span class="dt">y =</span> servings)) <span class="op">+</span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Alcohol type&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Number of servings&quot;</span>)</span></code></pre></div>
<p><img src="midterms_files/figure-html/unnamed-chunk-10-1.png" width="768" /></p>
</div>
<div id="question-6" class="section level3">
<h3>Question 6</h3>
<p>You are presented with data on the Titanic disaster of 1912 in a data frame <code>Titanic</code>, which cross-classifies survival vs death by class, sex, and age. Write down the <em>pseudocode</em> of the commands that will output a table comparing survival vs death counts for the following three scenarios:</p>
<ul>
<li>by sex</li>
<li>by sex and class and age</li>
<li>to answer the question if the “women and children”-first policy of the White Star Line Company (the company that ran the Titanic) held true or not.</li>
</ul>
<p>Note: you don’t need to calculate the output table, just write the pseudocode that would produce it where the more concise the pseudocode the better. Here is what the <code>Titanic</code> data looks like:\</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="kw">data</span>(Titanic)</span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="co"># Convert to tibble i.e. data frame</span></span>
<span id="cb14-3"><a href="#cb14-3"></a>Titanic &lt;-<span class="st"> </span>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb14-4"><a href="#cb14-4"></a><span class="st">  </span><span class="kw">as_tibble</span>()</span>
<span id="cb14-5"><a href="#cb14-5"></a></span>
<span id="cb14-6"><a href="#cb14-6"></a>Titanic</span></code></pre></div>
<pre><code>## # A tibble: 32 × 5
##    Class Sex    Age   Survived     n
##    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
##  1 1st   Male   Child No           0
##  2 2nd   Male   Child No           0
##  3 3rd   Male   Child No          35
##  4 Crew  Male   Child No           0
##  5 1st   Female Child No           0
##  6 2nd   Female Child No           0
##  7 3rd   Female Child No          17
##  8 Crew  Female Child No           0
##  9 1st   Male   Adult No         118
## 10 2nd   Male   Adult No         154
## # … with 22 more rows</code></pre>
<div id="solutions" class="section level4">
<h4>Solutions</h4>
<p>The key thing to note here is that the different combinations of <code>Class</code>, <code>Sex</code>, <code>Age</code>, and <code>Survived</code> are <em>pre-counted</em> in the <code>n</code> variable. Thus the <code>Titanic</code> data frame has only 32 rows. This is different than the <code>titanic</code> data frame from <a href="static/PS/PS05_solutions.html" target="_blank">PS05 Question 2</a> that has 2201 rows: one for each passenger.</p>
<p>So the data wrangling is a little different! Here we must <code>sum(n)</code> whereas in PS05 we used the <code>n()</code> summary function to count rows.</p>
<p><strong>Part a)</strong>: by sex</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="st">  </span><span class="kw">group_by</span>(Sex, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
## # Groups:   Sex [2]
##   Sex    Survived     n
##   &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;
## 1 Female No         126
## 2 Female Yes        344
## 3 Male   No        1364
## 4 Male   Yes        367</code></pre>
<p><strong>Part b)</strong>: by sex, age, and class</p>
<p>Nothing to do! We already have <code>Survived</code> (<code>"No"</code> vs <code>"Yes"</code>) counts split by these categories!</p>
<p><strong>Part c)</strong>: In retrospect this question is much harder than you can expect on the midterm. However if you’re curious:</p>
<p>First we need to have <code>Survived</code> (<code>"No"</code> vs <code>"Yes"</code>) counts for each <code>Sex</code> and <code>Age</code> combinations:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="st">  </span><span class="kw">group_by</span>(Sex, Age, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 8 × 4
## # Groups:   Sex, Age [4]
##   Sex    Age   Survived     n
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
## 1 Female Adult No         109
## 2 Female Adult Yes        316
## 3 Female Child No          17
## 4 Female Child Yes         28
## 5 Male   Adult No        1329
## 6 Male   Adult Yes        338
## 7 Male   Child No          35
## 8 Male   Child Yes         29</code></pre>
<p>Next we need to identify the “women and children”</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="st">  </span><span class="kw">group_by</span>(Sex, Age, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-3"><a href="#cb20-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb20-4"><a href="#cb20-4"></a><span class="st">  </span><span class="co"># Identify &quot;women and children&quot;. Shout out to Adriana B. for suggesting this step to me!</span></span>
<span id="cb20-5"><a href="#cb20-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">w_or_c =</span> Sex <span class="op">==</span><span class="st"> &quot;Female&quot;</span> <span class="op">|</span><span class="st"> </span>Age <span class="op">==</span><span class="st"> &quot;Child&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 5
## # Groups:   Sex, Age [4]
##   Sex    Age   Survived     n w_or_c
##   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;lgl&gt; 
## 1 Female Adult No         109 TRUE  
## 2 Female Adult Yes        316 TRUE  
## 3 Female Child No          17 TRUE  
## 4 Female Child Yes         28 TRUE  
## 5 Male   Adult No        1329 FALSE 
## 6 Male   Adult Yes        338 FALSE 
## 7 Male   Child No          35 TRUE  
## 8 Male   Child Yes         29 TRUE</code></pre>
<p>Next <code>group_by()</code> this new variable and get the sum of <code>n</code></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="st">  </span><span class="kw">group_by</span>(Sex, Age, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-4"><a href="#cb22-4"></a><span class="st">  </span><span class="co"># Identify &quot;women and children&quot;. Shout out to Adriana B. for suggesting this step to me!</span></span>
<span id="cb22-5"><a href="#cb22-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">w_or_c =</span> Sex <span class="op">==</span><span class="st"> &quot;Female&quot;</span> <span class="op">|</span><span class="st"> </span>Age <span class="op">==</span><span class="st"> &quot;Child&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-6"><a href="#cb22-6"></a><span class="st">  </span><span class="co"># Get counts for &quot;women and children&quot;:</span></span>
<span id="cb22-7"><a href="#cb22-7"></a><span class="st">  </span><span class="kw">group_by</span>(w_or_c, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-8"><a href="#cb22-8"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
## # Groups:   w_or_c [2]
##   w_or_c Survived     n
##   &lt;lgl&gt;  &lt;chr&gt;    &lt;dbl&gt;
## 1 FALSE  No        1329
## 2 FALSE  Yes        338
## 3 TRUE   No         161
## 4 TRUE   Yes        373</code></pre>
<p>Next compute the proportions. We haven’t done this much in class, but if you look in <a href="tips_and_tricks.html#prop">tips and tricks</a>, you’ll see this is one of the rare cases we use <code>group_by()</code>, but not followed by a <code>summarize()</code> but a <code>mutate()</code> instead:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="st">  </span><span class="kw">group_by</span>(Sex, Age, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-4"><a href="#cb24-4"></a><span class="st">  </span><span class="co"># Identify &quot;women and children&quot;. Shout out to Adriana B. for suggesting this step to me!</span></span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">w_or_c =</span> Sex <span class="op">==</span><span class="st"> &quot;Female&quot;</span> <span class="op">|</span><span class="st"> </span>Age <span class="op">==</span><span class="st"> &quot;Child&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-6"><a href="#cb24-6"></a><span class="st">  </span><span class="co"># Get counts for &quot;women and children&quot;:</span></span>
<span id="cb24-7"><a href="#cb24-7"></a><span class="st">  </span><span class="kw">group_by</span>(w_or_c, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-8"><a href="#cb24-8"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="st">  </span><span class="co"># Compute proportions:</span></span>
<span id="cb24-10"><a href="#cb24-10"></a><span class="st">  </span><span class="kw">group_by</span>(w_or_c) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-11"><a href="#cb24-11"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb24-12"><a href="#cb24-12"></a>    <span class="dt">total =</span> <span class="kw">sum</span>(n),</span>
<span id="cb24-13"><a href="#cb24-13"></a>    <span class="dt">prop =</span> n<span class="op">/</span>total</span>
<span id="cb24-14"><a href="#cb24-14"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
## # Groups:   w_or_c [2]
##   w_or_c Survived     n total  prop
##   &lt;lgl&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 FALSE  No        1329  1667 0.797
## 2 FALSE  Yes        338  1667 0.203
## 3 TRUE   No         161   534 0.301
## 4 TRUE   Yes        373   534 0.699</code></pre>
<p>Lastly, to make things easier to look at, let’s only look at <code>Survived</code> equals <code>"Yes"</code></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>Titanic <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="st">  </span><span class="kw">group_by</span>(Sex, Age, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="st">  </span><span class="co"># Identify &quot;women and children&quot;. Shout out to Adriana B. for suggesting this step to me!</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">w_or_c =</span> Sex <span class="op">==</span><span class="st"> &quot;Female&quot;</span> <span class="op">|</span><span class="st"> </span>Age <span class="op">==</span><span class="st"> &quot;Child&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="st">  </span><span class="co"># Get counts for &quot;women and children&quot;:</span></span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="st">  </span><span class="kw">group_by</span>(w_or_c, Survived) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-8"><a href="#cb26-8"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">sum</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-9"><a href="#cb26-9"></a><span class="st">  </span></span>
<span id="cb26-10"><a href="#cb26-10"></a><span class="st">  </span><span class="co"># Compute proportions:</span></span>
<span id="cb26-11"><a href="#cb26-11"></a><span class="st">  </span><span class="kw">group_by</span>(w_or_c) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-12"><a href="#cb26-12"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb26-13"><a href="#cb26-13"></a>    <span class="dt">total =</span> <span class="kw">sum</span>(n),</span>
<span id="cb26-14"><a href="#cb26-14"></a>    <span class="dt">prop =</span> n<span class="op">/</span>total</span>
<span id="cb26-15"><a href="#cb26-15"></a>  ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-16"><a href="#cb26-16"></a><span class="st">  </span><span class="co"># Only survived:</span></span>
<span id="cb26-17"><a href="#cb26-17"></a><span class="st">  </span><span class="kw">filter</span>(Survived <span class="op">==</span><span class="st"> &quot;Yes&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
## # Groups:   w_or_c [2]
##   w_or_c Survived     n total  prop
##   &lt;lgl&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 FALSE  Yes        338  1667 0.203
## 2 TRUE   Yes        373   534 0.699</code></pre>
<p>So yes, it seems “women and children first” did hold as seen by the 69.9% vs 20.3%.</p>
</div>
</div>
</div>
<div id="results-1" class="section level2">
<h2>Results</h2>
<p>Boxplot of scores with no whiskers below.</p>
<p><img src="static/images/midterm_II_distribution.png" width="750" /></p>
</div>
<div id="source-for-questions" class="section level2">
<h2>Source for Questions</h2>
<ul>
<li>Q1: Code from <a href="index.html#Lec10" target="_blank">Lec10</a> on color theory and <a href="https://moderndive.netlify.com/2-viz.html#two-categ-barplot" target="_blank">ModernDive 2.8.3</a> on <code>fill</code> aesthetic for barplots</li>
<li>Q2: <a href="https://moderndive.netlify.com/4-tidy.html#tidy-definition" target="_blank">ModernDive 4.2.1</a> on “tidy” data</li>
<li>Q3: <a href="static/PS/PS05_solutions.html" target="_blank">PS05 - Q1.a)</a></li>
<li>Q4: Code from <a href="index.html#Lec19" target="_blank">Lec19</a> on joins</li>
<li>Q5: Practice Midterm II with a few variations</li>
</ul>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
